version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ Therapy.API/Therapy.API.csproj
artifacts:
  files:
    - '**/*'